language: node_js
node_js: node
cache: npm
sudo: require
services:
    - docker

before_install:
    - docker build -t pauloeddias/docker-react -f Dockerfile.dev .

# script:
#     - docker run USERNAME/docker-react npm run test -- --coverage

script:
    - docker run -e CI=true pauloeddias/docker-react npm run test

# deploy:
#     # edge: true
#     provider: elasticbeanstalk
#     region: "us-west-2"
#     app: "<myapp>" 
#     env: "<My env>"
#     bucket_name: "<my bucket>"
#     bucket_path: "<myapp>"
#     on:
#         branch: master

#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY